#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Submit a LightGBM training job to Vertex AI using the custom container.

Usage:
  ./scripts/vertex_ai/submit_custom_job.sh [options] [-- <extra training args>]

Options:
  --image-uri URI         Container image URI (default derived from env)
  --machine-type TYPE     Vertex AI machine type (default: n1-standard-4)
  --region REGION         GCP region (default from GCP_REGION env)
  --project PROJECT       GCP project (default from GCP_PROJECT_ID env)
  --service-account SA    Service account email (default: estate-value-index-service-acc@PROJECT.iam.gserviceaccount.com)
  --dataset DATASET       BigQuery dataset (default: booli_features if --use-features, else booli_raw)
  --table TABLE           BigQuery table (default: engineered_features if --use-features, else listings)
  --display-name NAME     Vertex AI job display name (default autogenerated)
  --bucket BUCKET         GCS bucket for outputs (default from GCS_BUCKET env)
  --no-use-features       Disable --use-features flag (default enabled)
  --tune                  Add --tune to training args
  --debug                 Set BOOLI_DEBUG_VERTEX=true to emit debug bundle
  --dry-run               Print commands/YAML without executing
  --help                  Show this message

Examples:
  ./scripts/vertex_ai/submit_custom_job.sh --tune
  ./scripts/vertex_ai/submit_custom_job.sh --no-use-features --dataset booli_raw --table listings
  ./scripts/vertex_ai/submit_custom_job.sh -- --importance-threshold 0.01
USAGE
}

PROJECT_ID=${GCP_PROJECT_ID:-}
REGION=${GCP_REGION:-europe-north1}
BUCKET=${GCS_BUCKET:-}
IMAGE_URI=""
SERVICE_ACCOUNT=""
MACHINE_TYPE="n1-standard-4"
DISPLAY_NAME="lgbm-train-$(date +%Y%m%d-%H%M%S)"
USE_FEATURES=true
DATASET_ID_FEATURES="booli_features"
TABLE_ID_FEATURES="engineered_features"
DATASET_ID_RAW="booli_raw"
TABLE_ID_RAW="listings"
DRY_RUN=false
TUNE=false
DEBUG=false

EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --image-uri)
      IMAGE_URI=${2:?"--image-uri requires a value"}
      shift 2
      ;;
    --machine-type)
      MACHINE_TYPE=${2:?"--machine-type requires a value"}
      shift 2
      ;;
    --region)
      REGION=${2:?"--region requires a value"}
      shift 2
      ;;
    --project)
      PROJECT_ID=${2:?"--project requires a value"}
      shift 2
      ;;
    --service-account)
      SERVICE_ACCOUNT=${2:?"--service-account requires a value"}
      shift 2
      ;;
    --dataset)
      DATASET_ID_FEATURES=${2:?"--dataset requires a value"}
      DATASET_ID_RAW=${DATASET_ID_FEATURES}
      shift 2
      ;;
    --table)
      TABLE_ID_FEATURES=${2:?"--table requires a value"}
      TABLE_ID_RAW=${TABLE_ID_FEATURES}
      shift 2
      ;;
    --display-name)
      DISPLAY_NAME=${2:?"--display-name requires a value"}
      shift 2
      ;;
    --bucket)
      BUCKET=${2:?"--bucket requires a value"}
      shift 2
      ;;
    --no-use-features)
      USE_FEATURES=false
      shift
      ;;
    --tune)
      TUNE=true
      shift
      ;;
    --debug)
      DEBUG=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    --)
      shift
      EXTRA_ARGS+=("$@")
      break
      ;;
    *)
      echo "Unknown flag: $1" >&2
      usage
      exit 1
      ;;
  esac
done

: "${PROJECT_ID:?GCP_PROJECT_ID or --project is required}"
: "${BUCKET:?GCS_BUCKET or --bucket is required}"

IMAGE_URI=${IMAGE_URI:-"${REGION}-docker.pkg.dev/${PROJECT_ID}/vertex-training/lgbm-trainer:latest"}
SERVICE_ACCOUNT=${SERVICE_ACCOUNT:-"estate-value-index-service-acc@${PROJECT_ID}.iam.gserviceaccount.com"}

if [[ "$USE_FEATURES" == true ]]; then
  DATASET_ID=${DATASET_ID_FEATURES}
  TABLE_ID=${TABLE_ID_FEATURES}
else
  DATASET_ID=${DATASET_ID_RAW}
  TABLE_ID=${TABLE_ID_RAW}
fi

RUN_ID=$(date +%Y%m%d-%H%M%S)
MODEL_PREFIX="vertex-lgbm-${RUN_ID}"
MODEL_DIR="gs://${BUCKET}/vertex-ai/models/${RUN_ID}"
OUTPUT_URI="gs://${BUCKET}/vertex-ai/jobs/${RUN_ID}"

TRAINING_ARGS=("--data-source" "bigquery" "--model-dir" "${MODEL_DIR}" "--model-prefix" "${MODEL_PREFIX}")
if [[ "$USE_FEATURES" == true ]]; then
  TRAINING_ARGS+=("--use-features")
fi
if [[ "$TUNE" == true ]]; then
  TRAINING_ARGS+=("--tune")
fi
if (( ${#EXTRA_ARGS[@]} )); then
  TRAINING_ARGS+=("${EXTRA_ARGS[@]}")
fi

JOB_YAML=$(mktemp)
trap 'rm -f "$JOB_YAML"' EXIT

cat <<EOF > "$JOB_YAML"
serviceAccount: ${SERVICE_ACCOUNT}
baseOutputDirectory:
  outputUriPrefix: ${OUTPUT_URI}
workerPoolSpecs:
  - machineSpec:
      machineType: ${MACHINE_TYPE}
    replicaCount: 1
    containerSpec:
      imageUri: ${IMAGE_URI}
      args:
EOF

for arg in "${TRAINING_ARGS[@]}"; do
  [[ -z "$arg" ]] && continue
  printf '        - "%s"\n' "${arg//\"/\\\"}" >> "$JOB_YAML"
done

cat <<EOF >> "$JOB_YAML"
      env:
        - name: GCP_PROJECT_ID
          value: ${PROJECT_ID}
        - name: BIGQUERY_DATASET_FEATURES
          value: ${DATASET_ID}
        - name: BIGQUERY_TABLE_FEATURES
          value: ${TABLE_ID}
        - name: GCS_BUCKET
          value: ${BUCKET}
        - name: GCS_ENABLED
          value: "true"
        - name: BOOLI_DEBUG_VERTEX
          value: "${DEBUG}"
        - name: MODEL_ARTIFACTS_URI
          value: ${MODEL_DIR}
EOF

CMD=(gcloud ai custom-jobs create --project "$PROJECT_ID" --region "$REGION" --display-name "$DISPLAY_NAME" --config "$JOB_YAML")

echo "Submitting Vertex AI custom job with config: $JOB_YAML"
echo "Run ID: ${RUN_ID}"
echo "Model prefix: ${MODEL_PREFIX}"
echo "Model URI: ${MODEL_DIR}"
echo "Output URI: ${OUTPUT_URI}"

if [[ "$DRY_RUN" == true ]]; then
  echo "--- job.yaml ---"
  cat "$JOB_YAML"
  echo "--- end job.yaml ---"
  printf 'DRY RUN: '
  printf '%q ' "${CMD[@]}"
  printf '\n'
else
  "${CMD[@]}"
  STATUS=$?
  if [[ $STATUS -ne 0 ]]; then
    exit "$STATUS"
  fi
  echo "Vertex AI custom job submitted successfully"
  echo "Run ID: ${RUN_ID}"
  echo "Model prefix: ${MODEL_PREFIX}"
  echo "Model URI: ${MODEL_DIR}"
  echo "Output URI: ${OUTPUT_URI}"
fi
